version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hotel
    ports:
      - "3307:3306"  # Use 3307 to avoid local port conflict
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    working_dir: /app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Prevents host conflict
    working_dir: /app
    command: npm run dev
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mysql_data:
